# Generated by Django 6.0.5 on 2026-05-18 08:31

import django.db.models.deletion
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailysalesreport",
            name="total_order_items",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailysalesreport",
            name="total_quantity_sold",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailysalesreport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="DailySalesBatchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField()),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "chunk_size",
                    models.PositiveIntegerField(
                        default=reports.models.default_daily_sales_chunk_size
                    ),
                ),
                ("chunks_processed", models.PositiveIntegerField(default=0)),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("total_order_items", models.PositiveIntegerField(default=0)),
                ("total_quantity_sold", models.PositiveIntegerField(default=0)),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_runs",
                        to="reports.dailysalesreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
